// ESLint 9 flat config. eslint-config-next v16 exports native flat configs, so
// they can be spread directly — no @eslint/eslintrc FlatCompat shim needed.
import nextCoreWebVitals from 'eslint-config-next/core-web-vitals'
import nextTypescript from 'eslint-config-next/typescript'

const config = [
  {
    ignores: [
      '.next/**',        // build output
      'out/**',          // static export
      'next-env.d.ts',   // generated by Next
      '*.tsbuildinfo',
    ],
  },
  ...nextCoreWebVitals,
  ...nextTypescript,
  {
    rules: {
      // This app is a static export (`output: 'export'` with
      // `images: { unoptimized: true }` in next.config.ts), so next/image's
      // Image Optimization API is unavailable by design — plain <img> is correct.
      '@next/next/no-img-element': 'off',

      // React-Compiler-era guidance. The remaining hits are conventional patterns
      // (verify auth on mount, reset panel state when the selected movie changes,
      // poll download status) that would need the queue/auth flows restructured —
      // or a data-fetching library — to satisfy. Kept visible as a warning so it
      // doesn't gate CI, rather than turned off or papered over with disables.
      'react-hooks/set-state-in-effect': 'warn',
    },
  },
]

export default config
